name: Build and Release

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100  # Adjust version as needed
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyProject
        path: ./bin/Release/net7.0  # Adjust path based on your project structure
